### ISSUE TITLE
Add ability to download talks

### ISSUE THREAD

**Issue by bb4242** [bb4242/dharmaseed-android#2]

**Comment by jakewilson** [comment]
working on this now

**Comment by bb4242** [comment]
:+1: :tada:

**Comment by jakewilson** [comment]
Do you think the download button should be a menu item, like the star, or should it be an item in the actual activity? If the latter, I would place it on the right on the same horizontal as "center" and "date".

**Comment by jakewilson** [comment]
I've decided to place it in the activity, as opposed to the menu bar, because this is how google does it in Google Play.

**Comment by bb4242** [comment]
Sounds good to me!
